### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by noties** [noties/Markwon#65]
Create a plugin system that will allow easy customization and extension of current Markwon context.

<i>* This issue will be updated.</i> 
<i>** Branch `v3.0.0` will be created after `v2.0.0` release</i>

```java
final Markwon markwon = Markwon.builder()
    .use(new MyPlugin()) // maybe different name
    .build();
```

```java
public interface MarkwonPlugin {

    void configureParser(@NonNull Parser.Builder builder);

    void configureConfiguration(@NonNull SpannableConfiguration.Builder builder);

    void configureVisitor(@NonNull MarkdownVisitor.Builder builder);

    void configureImages(@NonNull AsyncDrawableLoader.Builder builder);

    @NonNull
    String processMarkdown(@NonNull String markdown);

    void beforeSetText(
            @NonNull TextView textView,
            @NonNull SpannableBuilder builder);

    void afterSetText(
            @NonNull TextView textView,
            @NonNull SpannableBuilder builder);
}
```

```java
public class MarkdownVisitor extends AbstractVisitor {

    public interface NodeVisitor<N extends Node> {
        void visit(@NonNull MarkdownVisitor visitor, @NonNull N node);
    }

    public interface Builder {

        @NonNull
        <N extends Node> Builder on(@NonNull Class<N> node, @NonNull NodeVisitor<N> nodeVisitor);

        @NonNull
        MarkdownVisitor build(
                @NonNull SpannableConfiguration configuration,
                @NonNull SpannableBuilder builder);
    }
}
```

### General
- [ ] Make `Markwon` methods instance specific
- [ ] Rename `SpannableMarkdownVisitor` -&gt; `MarkdownVisitor`
- [ ] Ensure that required by plugins methods and properties are accessible
- [ ] Update documentation web site and provide migration guide
- [ ] update sample applications to use plugin system
- [ ] make sure everything can still be achieved by using _old_ way (manually create parser, visitor, etc)

### Tables
- [ ] Remove table specific code from Visitor, Theme and Factory
- [ ] Create TablePlugin
- [ ] Move table feature to standalone module

### Strikethrough
*(maybe this functionality should be included in core features)*
- [ ] Remove specific code from Visitor, Theme and Factory
- [ ] Create StrikethroughPlugin
- [ ] Move strikethrough feature to standalone module

### Task list
- [ ] Remove specific code from Visitor, Theme and Factory
- [ ] Create TaskListPlugin
- [ ] Move task list feature to standalone module

### Images
- [ ] Move `AsyncDrawableLoader` to main `markwon` module (now it has no external dependencies)
- [ ] Make `AsyncDrawableLoader` abstract or an interface (no need for this abstraction to be in `AsyncDrawable`
- [ ] Create `svg` and `gif` media decoders modules
- [ ] Create network scheme handler module
- [ ] `AsyncDrawableLoader.Builder` should have `addMediaDecoder` method

### Html
- [ ] Provide a simple `HtmlParser` that will simply use `Html.fromHtml` (maybe include by default with the main module).
- [ ] Combine _somehow_ current `html-parser-impl` and `HtmlRendererImpl` (in main module). They are tightly connected anyway. Maybe by creating a new module `html` (keep current artifacts as-is)

### Syntax highlight
- [ ] Create syntax highlight plugin in current syntax highlight module

## Issues to resolve
- [ ] As `SpannableTheme` is tight with rendering context it should be decoupled from `Markwon` instance. Maybe create a `MarkwonFactory` that will accept `theme` as argument
- [ ] Maybe add a gradle plugin that will automatically add required dependencies (as their number grow) and generate an entry class (factory or something). But most likely additional modules will require additional configuration..
- [ ]  Handling of duplicate `Node` when registering NodeVisitors. Currently I see no way of allowing at max 1 override of a node (so, only one plugin can override it). Trying to register another would fail

**Comment by noties** [comment]
Closing in favor of #96
